### ISSUE TITLE
Android Messages stopped working

### ISSUE THREAD

**Issue by seedleen** [jiahaog/nativefier#1096]
Keeps telling me Chrome is outdated even though I just updated and restarted. I uninstalled and reinstalled Chrome too to see if that would fix it.

**Comment by ronjouch** [comment]
@seedleen help us help you: please include all the information requested by the [bug report template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by toddhuish** [comment]
@seedleen I had the same problem this morning. It has been a while since I updated Nativefier or node or npm but in the end I think my actual solution was simply 

`npm install -g nativefier`

Which bumped me from 7.6.9 to 42.0.2. This seems to require the newer electron which is how to get the newer Chrome
Then I had to re-nativeify Messages for Web

`nativefier --platform "mac" --icon android-messages-logo.png --name "Google Messages" "https://messages.google.com/web" --honest --disable-dev-tools --single-instance`

**Comment by ronjouch** [comment]
@toddhuish thanks for chiming in!

By the way, since Nativefier 42.x, Nativefefier will periodically ask for a re-build. Nativefier is Chromium under the hood, and browsing with a super old Chromium is dangerous. See https://github.com/jiahaog/nativefier/releases/tag/v42.0.0 .

> **\[BREAKING CHANGE\] Warn on old Electron/Chrome (fix [#556](https://github.com/jiahaog/nativefier/issues/556)) (PR [#1076](https://github.com/jiahaog/nativefier/pull/1076))**  
> :warning: Users packaging kiosk apps running unattended on internal websites,  
> see [doc for flag `--disable-old-build-warning-yesiknowitisinsecure`](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#disable-old-build-warning-yesiknowitisinsecure)

**Comment by seedleen** [comment]
Thanks to both of you, but I am not a developer so I don't understand any of that.
