### ISSUE TITLE
Cannot retrieve app icon when not using public domains

### ISSUE THREAD

**Issue by cmmata** [jiahaog/nativefier#119]
Hi

Is it possible to use nativefier with my own DNS instead of Google's? I tried to run nativefier with one of my company's internal webapps, and I got this error:
Cannot automatically retrieve the app icon: Get https://xx.xx.com: dial tcp: lookup xx.xx.com on 8.8.8.8:53: no such host

As it's a internal application, the URL is not in public DNS, but it is in my computer DNS (a local server).

**Comment by jiahaog** [comment]
Yeap, this is expected behaviour. It's because I'm running the [bestIcon](https://github.com/mat/besticon) service on my Digital Ocean droplet, and the icons are retrieved from this API. Naturally the droplet would be unable to access your intranet. I plan to port the icon retrieval so that it is self-contained in the near future (when I have more time), could you try to manually add the icons with the `--icon` flag instead?

**Comment by cmmata** [comment]
Yes, I saw that --icon flag. But as we have several internal applications, I was asking if there's an option to use another DNS to avoid downloading each icon manually. Don't worry, I'll do it that way until you have that free time. :)
