### ISSUE TITLE
[Suggestion] Minimize to tray?

### ISSUE THREAD

**Issue by devils-shadow** [jiahaog/nativefier#127]
Saw some work as been started on allowing tray minimization. Currently using nativefier for WhatsApp and would love to be able to have it close to the tray when I click the X instead of having it instantly get killed.

As a side-suggestion: any way to hide/toggle/remove the window border? Maybe a toggle of some sort that only makes it show up when you press Alt.

**Comment by jiahaog** [comment]
Yup, some work has gone into the tray minimization but is not complete yet. What do you mean by hiding the window border?

**Comment by M-Picco** [comment]
Hi. Sorry if this was already closed. Is the tray feature working? When I forked the project It didn't seem to have it, unless I missed some option or anything else.

**Comment by jiahaog** [comment]
Nope, it isnt working. It's abit complicated to get to to work cross-platform, and because there are some bugs in the way the icon is set I wish to fix that before adding the tray feature.

**Comment by M-Picco** [comment]
Oh, that explains it. When I first tried the application the one thing that bothered me was this, so I forked it and started working on the tray feature (I didn't experience much problems with the icon since I used a hardcoded path). The only matter is that it's tested on Windows only, I don't have much knowledge about IOS and Linux. However, I saw that someone already made a pull request with the feature so I think I'll wait for when It's done.

Thanks for the response.

**Comment by M-Picco** [comment]
Hello. Sorry to bother again. Two questions:

 - What are the complications/specifics to be taken into account for each platform?
 - What are these bugs with the icon?

I've been working on this feature (at least to use it privately). But before making a pull request I'd like to check if these things are considered/working.

I could test it on windows 10 and worked fine.

Thanks.

**Comment by jiahaog** [comment]
Hi there! Some work has already gone into the dock in #110 but I've unmerged it because of some issues with the icon not being done properly, and that fix has a few bugs for OSX and Windows.

I can't really remember the specifics, but off the top of my head, I know that there are some logical bugs on Windows; the icon for the `.exe` is not set, problems with `.ico` files, etc. I want to make sure that such logical errors are fixed before I add in the dock function, and I'll probably have time to work on this next week during my break.

**Comment by M-Picco** [comment]
Welp. Had I gotten a month earlier my pull request would have been useful. I'll se if I can find these bugs. If I can work them out I'll make a pull request.
