### ISSUE TITLE
[ Enhancement ] Use the favicon.ico as the app icon

### ISSUE THREAD

**Issue by jacobsmith** [jiahaog/nativefier#16]
I would love for the app to automatically fetch the `favicon.ico` image from the destination URL and convert that to the icon used by the OS. If there's any buy-in on this, I wouldn't mind making the PR for it later, but that could be a fairly easy way to get more contextual icons without having to specify them manually.

**Comment by jiahaog** [comment]
Hi, I initially had this idea as well, as having to manually convert an icon file for the app simply goes against the simple nature of the command, and it would be extremely cool if the icon is packaged for you. The issue I'm having is converting the favicon or whatever image to the `.icns` format as required by the library I'm using to package the app, I'm not really sure if there are node.js libraries to do that, and I'm not familiar with how to do so with other libraries. 

Also, I think it would be great if some sort of string matching is implemented for the app name and high resolution icons could be sourced from something like [gilbarbara/logos](https://github.com/gilbarbara/logos) instead, so that the native experience for the user is seamless.

**Comment by jacobsmith** [comment]
Yeah, I just looked at `icns` for the first time, and it's not exactly well-supported or standard (: I did find a node package that calls out to an API that says it will convert it automatically, though I'm not sure if there's a License or EULA that doing it programatically like this would violate. https://github.com/laander/image-to-icon-converter

I'll keep looking at this later; definitely a bit more nuanced than I originally thought!

**Comment by FanaHOVA** [comment]
I've just [created a repo](https://github.com/FanaHOVA/nativefier-apps-icns/) to collect icons. I'm using this website: https://iconverticons.com/online/

**Comment by CatTail** [comment]
How about this one, [How to manually create icns files using iconutil?](http://stackoverflow.com/questions/12306223/how-to-manually-create-icns-files-using-iconutil). It's ok to use native command rather than Nodejs module because it's OSX related.

**Comment by jacobsmith** [comment]
@CatTail That could be good for OSX, but I think this repo is trying to be cross-compatible with Windows and Linux as well. It could be a possible OSX only option until a cross-compatible implementation is found.

**Comment by simonweil** [comment]
+1 for an automatic icon.
This is quite a blocker for me as I can't differentiate all my open apps from one another.
(I currently use fluid for this which has many problems).

**Comment by JuhQ** [comment]
+1 because I'm lazy

**Comment by jiahaog** [comment]
Nativefier will now automatically infer the app icon for the target url, as of `v6.8.0`, yay!

**Comment by jiahaog** [comment]
@FanaHOVA I'm going to create a [repo](https://github.com/jiahaog/nativefier-icons) with a server so that nativefier can easily retrieve popular app icons, and it would be easier for me to manage the naming conventions as such, thanks for the idea!
