### ISSUE TITLE
Doesn't support authentication

### ISSUE THREAD

**Issue by DarwinAwardWinner** [jiahaog/nativefier#19]
I have some web pages on my personal server, e.g. Transmission, that require HTTP authentication before loading the page. When I try to package these as apps using nativefier, they just give a 401 page without any login prompt.

**Comment by jiahaog** [comment]
It appears that Electron supports this since atom/electron#3250, I'll look into implementing this with a small window, thanks for the feedback!

**Comment by tennisgent** [comment]
I got this same thing with `feedly.com`. I tried to wrap it and the application works beautifully, until I try to login. It requires OAuth2 authentication, which requires that the application open a separate tab for the OAuth2 provider (Google, Facebook, etc). When the application tries to open this window, the authentication page opens in Chrome, which never gets back to the application to store the cookie.

Otherwise, this is a very sweet tool! Thanks for putting it together. :)

**Comment by dansowter** [comment]
Some issue for Facebook auth while "nativefier"ing Habitica.

**Comment by mdamjanic7** [comment]
I've tested this with Feedly, and it works great, but when trying to do Google log in to Asana (app.asana.com), it simply opens a Safari window, and stays there.

**Comment by DarwinAwardWinner** [comment]
My original report was about basic HTTP authentication dialogs. I'd imagine that Google/Facebook/etc. logins that open separate browser windows would require a completely different fix.

**Comment by jiahaog** [comment]
You can now use the right click context menu to force certain authentication links to open in the same Electron process, and hence login will work for most OAuth sites. 

@mdamjanic7 Asana seems to be an exception and I have no idea how to get it to work though :(

**Comment by jiahaog** [comment]
If anyone can figure out how to get certain OAuth sites like Asana to work please voice out, closing this issue for now.

**Comment by jiahaog** [comment]
I've created #164 which consolidates all problems with logging in!

**Comment by tianhuil** [comment]
This is a narrow-cast solution which wokred for me and keeps non-google-login links opening externally for **asana**:
```
nativefier --name "Asana" --internal-urls "accounts\.google\.com.*" https://app.asana.com/
```
