### ISSUE TITLE
customize menu

### ISSUE THREAD

**Issue by philippkeller** [jiahaog/nativefier#219]
apologies, this is not an issue but a question but I couldn't find any forum for this:

Is it possible to add menu items which trigger a JS function and add a keyboard combination to it?
I've seen [this comment](https://github.com/jiahaog/nativefier/issues/168#issuecomment-217431030) but I cannot find any `[app_folder]/resources/app/lib/main.js` folder after firing the `nativefier` command

**Comment by philippkeller** [comment]
after some more digging I assume that nativefier is just for wrapping websites 1:1, for more customizing you need to start a electron app yourself. If anyone is interested: this is a minimal setup with keybindings some DOM mutations and a custom logo: https://github.com/philippkeller/goodbudget-electron

**Comment by Thatkookooguy** [comment]
@philippkeller well.... yes. By definition, that's what nativefier is for. But ofc, because this project is open source, you can read the code and change what you want.

If you want all the basic functionality to act the same (url's open in default browser, badge on dock, etc), you can start with nativefier and improve on it or start with electron and just use similar solutions for some of those stuffs.

have fun! 😄

**Comment by philippkeller** [comment]
what was not clear to me: how do you make nativefier to leave the electron project lying around?

**Comment by Thatkookooguy** [comment]
what do you mean? I'm not sure I understood the question

**Comment by philippkeller** [comment]
when I call nativefier all I get as an output is the actual os X app, but I'd want to have the electron project so I could customize things further

**Comment by Thatkookooguy** [comment]
in order to change nativefier to your own needs, you need to:
1. Fork the nativefier project
2. Clone it to your own computer:
```
$ git clone <YOUR_FORK_URL>
$ cd nativefier
```

and then, just do what is written in the [development guidelines](https://github.com/jiahaog/nativefier/blob/development/docs/development.md) (mimus the `First clone the project` section)

**Comment by philippkeller** [comment]
thanks!

**Comment by jiahaog** [comment]
You could use nativefier to build the app, right click on the packaged app > show package contents and change the generated javascript files from there as well. (Though they are compiled and bundled together)
