### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by scrambled2k3** [jiahaog/nativefier#247]
### Description

Keep getting this error in the console for an app I generated.  When the app opens, I am only presented with a blank white screen.  So I opened up devtools and see this error.  I have tried creating to 2 times and get this same result.
### Steps to Reproduce Issue

run this command:

```
nativefier "https://beta.processplan.com"
```
### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js: `v5.4.1`
- OS: `Windows 10`

**Comment by ronjouch** [comment]
Hey @scrambled2k3 thanks for the feedback. I registered to your app and could sign in, everything looked smooth under Nativefier 7.1.0 and Electron 1.6.6 (`nativefier -e 1.6.6 "https://beta.processplan.com"`)

Note above I bundled using a recent electron version, feedback welcome if the problem was due to the old electron used by default. And yes we'll soon be shipping a new nativefier defaulting to a more recent electron by default :) .
