### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by Jamesking56** [jiahaog/nativefier#303]
Does the built-in Chrome still update automatically or is it locked to a specific version? The reason I ask is I want to get this installed into some big organisations who only install once. We have a web app but I think they will use it more if it is natively installed on their systems.

Thanks.

**Comment by quanglam2807** [comment]
@Jamesking56 You can try my app https://getwebcatalog.com. It might be what you are looking for.

**Comment by ronjouch** [comment]
@Jamesking56 thanks for the feedback! There's no automatic update: yes a nativefied app is locked to a specific version of Chrome/Electron, which you can specify at build time using the `--electron-version` option (see `nativefier --help` for the full list of options). There's no plan to change that, as all the machinery for this is part of the nativefier builder and not the nativefied app.

However,

* You can upgrade an app by just re-running nativefier at the same place with a newer `--electron-version`
* Since you mention it's for enterprise deployment, what would make sense is that administrators periodically do this re-bundling (to benefit from Electron/Chrome security & perf improvements) and deploy the newly-bundled app to the fleet of machines, using Active Directory or whatever they use for that.
