### ISSUE TITLE
Add minimize-to-tray option / support 'running in background'

### ISSUE THREAD

**Issue by vandykew** [jiahaog/nativefier#304]
### Description

I would like to be able to Click the X and have it minimize to the system tray 

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v6.9.2`
- OS: `Win 10`
- Architecture `X64`

**Comment by wvamdyke** [comment]
Any ideas on this ?

**Comment by eyarz** [comment]
You can easily implement it by yourself.
just edit the app/src/components/mainWindow/mainWindow.js script so ['close' event](https://github.com/jiahaog/nativefier/blob/development/app/src/components/mainWindow/mainWindow.js#L175) will minimize the app instead of closing it:
mainWindow.webContents.minimize()

**Comment by zhongyiwei** [comment]
mainWindow.webContents.minimize()
This return TypeError, mainWindow.webContents.minimize is not a function
Still not sure how to hide create a tray icon and hide to tray..

**Comment by eyarz** [comment]
you are right, my mistake, it is [mainWindow.minimize()](http://electron.atom.io/docs/all/#winminimize).

if you want to minimize to tray (next to windows clock) here is an example:
https://github.com/hokein/electron-sample-apps/blob/master/tray/main.js

**Comment by leovarmak** [comment]
@ronjouch Any ETA as to when can this be added ?

**Comment by ronjouch** [comment]
> *"Any ETA as to when can this be added ?"*

@leovarmak none! We (maintainers) are resuming maintenance since the original maintainer no longer has time for that. There's lots to do and we're far away from new features, as currently focusing on issue triaging, doing a big round of deps updates & testing, existing PRs, simplifying the build process, and bugfixes.

But the feature is clear and APIs are here, so anyone with the will and time for that can try giving it a stab, PRs will be much welcome :)

**Comment by leovarmak** [comment]
@ronjouch I haven't tested this but the tray option is finally added ?

**Comment by Gregory-K** [comment]
@leovarmak the tray option is finally added
I just tested it.  
Until a stable release, you have to use the latest code https://github.com/jiahaog/nativefier/blob/master/docs/development.md
