### ISSUE TITLE
Add --x/--y options defining start position of app

### ISSUE THREAD

**Issue by ivo1981** [jiahaog/nativefier#325]
I am unable to set the start position for the app.
I use a frameless app which also makes it unmovable. (this is good in my case)
however the app defailts to center (electron default). 

I think this is due to: 
x: mainWindowState.x,
y: mainWindowState.y,
in main.js.
If I change it to x: 0, y: 0, this has no effect.

Any ideas on how I can fix this?

Thank you,
Ivo

**Comment by ivo1981** [comment]
Ok I have a work around for now:
I changed the x and y values of main.js of the generated app. Was quite a bit of code to go through since I didn't know what I was looking for.

The solution would be to add the x and y args to the options/switches for generating the app.

**Comment by ronjouch** [comment]
@ivo1981 thanks for the feedback! Nativefied apps remember their position from their last run, but you say the app is unmovable due to disabling the window top bar (I assume you used `--hide-window-frame`).

It makes sense that if nativefier has `width` and `height` flags, it could have `x` and `y` ones too.

Glad you found a workaround; alternatively, you could have moved the window even without a window bar:

* Under Linux, just Alt+click/drag the window.
* Under macOS, see [this stackoverflow discussion](https://superuser.com/questions/223318/mac-os-x-altleft-click-move-window-possible-in-10-5-and-up) or [Alt-Drag](https://github.com/bahamas10/Alt-Drag).
* Under Windows, use [AltDrag](https://stefansundin.github.io/altdrag/).

**Comment by ivo1981** [comment]
Just want to say thanks for your efforts so far.
It seems you are picking up the support nicely!

I'll try to make a piece of code that will make the x and y options work, but in all honesty I'm not a real coder yet. At the moment I'm in the stage where I'm starting to 'borrow' less and less code from others and writing more of it my self.
Thanks so far!

**Comment by ronjouch** [comment]
@ivo1981 welcome, glad it's appreciated 😸! Cool, go ahead and try a fix, feel free to ask for help and don't hesitate to submit a PR early, we'll discuss your code there.
