### ISSUE TITLE
Unread badge on application icon under Ubuntu Unity

### ISSUE THREAD

**Issue by mihab** [jiahaog/nativefier#332]
### Description
This is a feature request! Love the app, use it for both WhatsApp and Messenger!

I really like the way on macOS you see a little read dot indicating that you have unread notifications as in:

![dock](https://github.com/jiahaog/nativefier/blob/development/screenshots/dock.png?raw=true)

However the same behavior does not occur on Ubuntu Unity, if you are not around when the message arrives you are in no way notified that you have unread messages waiting. Is there a way to make a red dot like on macOS appear on Ubuntu as well...or at least make the icon somehow indicate there is a notification pending?

I believe in Unity you can make the dock icon 'wiggle' somehow, in case the window needs attention, if I am not mistaken.

**Comment by ronjouch** [comment]
Closing as Ubuntu moved from Unity to GNOME Shell. PR still welcome to satisfy remaining Unity users 🙂.

**Comment by herophuong** [comment]
The API for badge notification is still the same, with the use of a dock extension in newer Ubuntu. KDE also uses the same API, so having this also helps KDE users too. Several third-party docks like Cairo-Dock, Plank also support same API.

https://wiki.ubuntu.com/Unity/LauncherAPI

I hope this one can be re-opened so we can track the feature, rather than let it slides away.
