### ISSUE TITLE
Poll: Nativefier use cases

### ISSUE THREAD

**Issue by quanglam2807** [jiahaog/nativefier#333]
Hi guys, I'm working on [WebCatalog](https://getwebcatalog.com/) which shares many similarities with Nativefier. At the moment, unlike Nativefier, you cannot freely install any app you like but soon, it will change. I'm looking forward to create a CLI for WebCatalog. 

But WebCatalog works differently as it uses one single Electron instance instead of using independent instance for each app. So do you guys prefer Nativefier approach or WebCatalog? And what are your use cases? If Nativefier still offers advantages over WebCatalog, I'll will make a forked version of this repo and continue the development. If not, I'll concentrate my time on improving WebCatalog.

**Comment by quanglam2807** [comment]
#326 #327.

**Comment by BTooLs** [comment]
From what I see webCatalog's destinations are the end users, as nativifier for devs/more tech users. I for example use it to wrap the website and offer them as download version, so web catalog is not an alternative for me.

**Comment by quanglam2807** [comment]
@BTooLs So when you use Nativefier, how do you provide updates? For example, you create an app for your website and release to your users. Then you need to update Chrome. How do you do it? If the development of Nativefier moves on, do you think it's better to make it works specially for devs?

**Comment by BTooLs** [comment]
I haven't reached that far, I am just starting, but I will not concern about the Chrome version, we are still using JS5 (babel) because not all the users have new browser versions, so this problem will take at least 1Y to take effect in which it will became irrelevant (OS reinstall, user buy new PC etc). Mainstream web apps are always living in the past :))

As for Nativifier I think there's already a long list of features request in the issues. My first one was only the output size. 
Thanks, for me it just worked, and the inject feature solved some issues, including a way to distinguish desktop vs web sessions.

**Comment by quanglam2807** [comment]
@BTooLs Thank you! It's clear now.
