### ISSUE TITLE
Windows appData path based on project location (Bug or feature?)

### ISSUE THREAD

**Issue by BTooLs** [jiahaog/nativefier#334]
### Description
Changing a build path, on windows 10 triggers a new AppData folder.
On Linux build this behavior doesn't exists, on Mac I can't test.

Is there any way to keep the same storage, or to move it into the build folder? 
Related #147 #144 #42 #149 those tickets are marked as Solved but I can't see the option/feature/flag.

### Steps to Reproduce Issue
Make a windows x64 build
Open the build and close it
rename the folder or move it
open it again
2 folders appears, users data is lost (from his perspective)

> C:\Users\user\AppData\Roaming\app-nativefier-65c69f
C:\Users\user\AppData\Roaming\app-nativefier-a252ba

### Specifications
 nativefier --version 7.0.1
 node --version v6.10.0
npm --version 3.10.10

- OS: windows
- Architecture x64

**Comment by ronjouch** [comment]
> *"Is there any way to keep the same storage, or to move it into the build folder?
Related #147 #144 #42 #149 those tickets are marked as Solved but I can't see the option/feature/flag."*

Hola @BTooLs, thanks for the report! There's no option, since https://github.com/jiahaog/nativefier/pull/149 the storage location changed from being random to deterministic based on the app URL. So as long as you re-run nativefier with the same URL, the appdata folder should be used.

This is a feature, not a bug, it means for example it's possible to upgrade to a newer electron/chrome by simply re-running nativefier at the same place and with the same URL.

Then you are mentioning renaming the build folder changes the appdata folder?! I just tested that but couldn't reproduce the issue, are you sure about it / can you provide more details?

**Comment by BTooLs** [comment]
Sorry there was a false alarm. I think my windows is broken, some functions are not working properly.
I tried to reproduce it on another machine with the same Windows version and is not happening.

Thanks.
