### ISSUE TITLE
update dock icon when favicon changes

### ISSUE THREAD

**Issue by lsmith77** [jiahaog/nativefier#367]
### Description
For example facebook updates the favicon to show the unread notifications status. Would be nice to propagate this to the OSX dock.

Related to https://github.com/jiahaog/nativefier/issues/332

### Steps to Reproduce Issue
* Setup nativefier with facebook.com
* Have some unread notifications, 
* OSX dock icon is not updated

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `7.3.1`
- Version of Node.js (run `$ node --version`): `v7.10.0`
- OS: `OSX 10.11.6`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by ronjouch** [comment]
Hi @lsmith77, thanks for the feedback!

- Nativefied apps running on macOS already support using a dock icon badge to indicate count of in-app notifications/messages, as long as you pass the `--count` flag (see `nativefier --help` for the full list of options). This depends on the page updating the title with digits surrounded by parentheses, for example `Facebook (8)`. [Code here](https://github.com/jiahaog/nativefier/blob/8f78dd03af47155c950dd6af8cef9599bd77f3cc/app/src/components/mainWindow/mainWindow.js#L178-L187), give it a try and please do report back if it's broken 😃.
- Regarding updating the whole dock icon with a favicon, I'm not sure that's a good idea, because the high-quality dock icon you end up with (passed via `--icon` or inferred via nativefier-icons) might end up being overwritten with a crappy 64x64 favicon, which will look horrible in the dock.

**Comment by lsmith77** [comment]
ok thx for the feedback

**Comment by lsmith77** [comment]
for the record .. the parameter is `--counter`
