### ISSUE TITLE
Copy/paste/cut should be accessible from context (right-click) menu

### ISSUE THREAD

**Issue by petrk94** [jiahaog/nativefier#384]
### Description
Hello,

I would like to know why the context menu doesnt offer copy/paste/cute ?
My client would like to use it, instead of keyboard shortcuts.
Thanks

### Steps to Reproduce Issue
Open a working nativefied App and make a right click on your mouse

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `7.4.0`
- Version of Node.js (run `$ node --version`): `v7.4.0`
- OS: `Windows`
- Architecture `x64`

**Comment by ronjouch** [comment]
Thanks for the feedback, @petrk94 ! Copy/paste/cut are available from the `Edit` menu, if you prefer a mouse access to keyboard shortcuts. Regarding adding these to the context menu, I admit I'm not fond of the idea, I'd rather keep it uncluttered.

Disapproval / attempts to convince us otherwise welcome 🙂.

**Comment by petrk94** [comment]
Hey @ronjouch, I understand that now, but this doesnt look very modern, if the people need to mark a text, go to the Edit in the menu bar (what is necessary to be visible, otherwise you can not access the edit feature) and click copy/paste/cut. You understand what I mean? It should be native in every App, because its the usablity what user expect, in every browser you mark a text, make right click and it appear the context option to copy this text. If this is not working in the App, why people should prefer the App, instead of the browser using a bookmark? 
You understand what I mean. Im sorry if its listen that Im angry, Im not^^.
Ps. How I can edit the fields in the menubar?; exist a way to update the nativied App files?

Thanks

**Comment by ronjouch** [comment]
@petrk94 no problem, there's nothing angry about your good feedback 👍. Alright for the "it's the expected usability from other browsers". To anyone working on this: to avoid extra clutter, please no constant cut/copy/paste entries, only what's appropriate to the context (like Firefox/Chrome do). When right-clicking...

- ... in the page, with no selection: nothing
- ... in the page and out of a textfield, with an active selection: copy
- ... in a textfield, with no selection: paste
- ... in a textfield, with an active selection: cut/copy/paste

@petrk94 if you have the time/desire/knowledge, pull request welcome, our [development guide](https://github.com/jiahaog/nativefier/blob/master/docs/development.md) will get you started. Otherwise keep your fix expectations low, there's no guarantee someone will work it anytime 🙂.

**Comment by petrk94** [comment]
@ronjouch unfortunately I dont have experience in developing this kind of tool.
Is there something like a good documented tutorial where to begin?

**Comment by ronjouch** [comment]
> *Is there something like a good documented tutorial where to begin?*

@petrk94 try looking for node.js tutorials/videos, and play with the [Electron](https://electron.atom.io/) API.

**Comment by sb2059** [comment]
Is the fix as simple as what's specified here? https://blog.avocode.com/blog/4-must-know-tips-for-building-cross-platform-electron-apps

If so, this is a low-cost high-value flag you could add.

**Comment by mfl5** [comment]
This is definitely a needed feature for me and my team.

Additionally to standard copy paste (ctrl+c / ctrl+v) and right click copy/paste:

The "Copy Link Address" and "Copy Email Address" features of the right click context menu in google chrome are invaluable and I'd recommend including that as well.

A side note, if people are worried about their apps right click context menu being clean why not just have a command line option for whether or not to enable copy/paste features.

**Comment by bacongravy** [comment]
I believe this issue would be resolved by PR #579, which adds a standard context menu that includes cut/copy/paste

**Comment by ronjouch** [comment]
Fixed by https://github.com/jiahaog/nativefier/pull/588
