### ISSUE TITLE
Detect as bad files or viruses message

### ISSUE THREAD

**Issue by dipenpatel235** [jiahaog/nativefier#391]
### Description
Hello..
i am trying to build desktop app of my url.
but issue is  bad files or viruses message when used on another pc

### Steps to Reproduce Issue

`nativefier --arch 'ia32' --platform "windows" --name "Hello" "https://www.myhost.com" -i ./Logo_Final-notext.png --user-agent "webapp_desktop_v1.0.1" --disable-dev-tools --crash-reporter "https://damp-fjord-XXXXXX.herokuapp.com/"`

after that one folder created and then that folder to i am creating one exe using setup factory / Inno setup for create desktop shortcut and i click installation.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.0`
- Version of Node.js (run `$ node --version`): `v6.10.2`
- OS: `centos 7`
- Architecture `64 bit`

**Comment by ronjouch** [comment]
@dipenpatel235 thanks for the feedback! But please be more precise: you say you see *"bad files or viruses messages when used on another pc"*.

* What are these virus messages when used on another PC?
* Which application emits them? An antivirus/antimalware? The OS? Are their signatures databases up-to-date?
* When are these message emitted? At install time by your installer, or at run time?
* If at install time, since you say you are *"creating one exe using setup factory / Inno setup"*, are you sure your installer isn't the culprit?

**Comment by dipenpatel235** [comment]
lets suppose mine installer is culprit so you have any option and any tool using that i can create one click installation and create desktop shortcut of my app ?

giving you message seen by  antivirus
Thanks

**Comment by ronjouch** [comment]
@dipenpatel235 InnoSetup is good. Try [NSIS](http://nsis.sourceforge.net/) too, or go the Windows native way by [creating a MSI](https://encrypted.google.com/search?hl=en&q=howto%20msi). Installers resort to special tricks to minimize file size while remaining executable, your best bet to avoid this kind of false positive is certainly the MSI way. Careful, MSIs are (or at least used to be) complicated, don't do it blindly following the documentation, find a good tutorial / tool that helps you building your package. Good luck 🙂.

**Comment by dipenpatel235** [comment]
ok...thanks
i dont think issue in your build package. but i think issue in after build exe.
so may be issue in exe builder software like NSIS and InnoSetup 
both in detected as virus related alert or badfile relate alert.

here i have attached screenshot of build exe from NSIS.

![virus_alert](https://user-images.githubusercontent.com/8135097/27506164-5e6d1c24-58d0-11e7-9429-d1fc692a8aad.png)
