### ISSUE TITLE
Feature request: Allow multiple windows

### ISSUE THREAD

**Issue by hanselke** [jiahaog/nativefier#399]
### Description

nativefier is great for creating desktop apps for the webapps i use normally, but it would be way better if we can bundle up many webapps inside the app.

Yes it would create the 'tabs' issue just like in chrome browser.... but it would be the one app that i run when i start my daily workflow instead of having to restart all the chrome tabs (which would be used for other stuff as well)

**Comment by ronjouch** [comment]
@hanselke thanks for the feedback.

Closing, as that's opposite of the direction followed by nativefier (isolated apps, single window, no tabs, etc). Yes, use your browser. And to achieve *"it would be the one app that i run when i start my daily workflow instead of having to restart all the chrome tabs (which would be used for other stuff as well)"*, maybe look at a combination of these to fit your workflow:

* Extensions
* Chrome's command-line arguments: `chrome http://site1.com http://site2.com http://site3.com`
* Chrome profiles
