### ISSUE TITLE
How to check if the page is running in nativefier windows app or website

### ISSUE THREAD

**Issue by tarunbatta** [jiahaog/nativefier#423]
### Description

I have a website for which I have create a windows app as well using nativefier. The base code is in AngularJs. I wanted to identify if the user is using my website or windows app. Is there any way?

### Steps to reproduce issue
NA

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: NA
- Version of Nativefier (run `nativefier --version`): 7.4.0
- Version of node.js (run `node --version`): 8.1.0
- OS: Windows
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
@tarunbatta nope. We have a `--honest` flag that *"prevents the nativefied app from changing the user agent string to masquerade as a regular chrome browser"* but it's intentionally off by default, because the contrary would certainly cause breakage for websites doing sleazy useragent sniffing.

Now, if I may, *why* do you want to differentiate between a nativefier client vs. a regular browser client?

**Comment by tarunbatta** [comment]
Thanks for the quick response. 

To answer your question, the use case is to capture the traffic for analytics.

**Comment by githubbob42** [comment]
I have the same issue where I need to detect if my app is a Nativefier app.  In my case, I am unable to view a PDF file within the Nativefier app (regular desktop Chrome works just fine). 
 It appears the desktop/regular browser Chrome has a builtin extension that allows viewing of PDF's in the browser.  This extension is not available in the Android version of Chrome, so our web app has special code to handle that.  I need to run the Nativefier app through the same code path as for Android in order to view PDF's in our app.

In order to accomplish this, I have modified the userAgent string to append `Nativefier` at the end and I test for it in our app (in addition to `Android`).  This seems to work, but I wasn't sure if there was another (more appropriate) way to do this without monkeying with the userAgent string.
