### ISSUE TITLE
Google cast support

### ISSUE THREAD

**Issue by chrisgross** [jiahaog/nativefier#476]
Are there any plans to add Google cast support? Not necessarily to add a UI option for casting the contents of an arbitrarily nativefied site, but to simply support any website with built-in cast support. Google Play Music immediately comes to mind, but others like Netflix, as well. I thought that since Chrome/Chromium was the underlying technology, it would work out of the box, but it doesn't look like it.

**Comment by ronjouch** [comment]
Hey ho @chrisgross, thanks for the interest and feedback 🙂.

Would be neat yes, but closing, as depending on upstream https://github.com/electron/electron/issues/869 who say acknowledge the issue/request *"since there are lots of requests of it, but it doesn't not indicate we are going to work it."*
