### ISSUE TITLE
WhatsApp just stop working

### ISSUE THREAD

**Issue by joserobleda** [jiahaog/nativefier#50]
I tried to package Whatsapp in a Mac yesterday and it works, in the version `6.4.0`, but now it doesn't anymore. I'm tried the `--pretend` and also the new `--honest` flag, but none works.

**Comment by jiahaog** [comment]
Oh, I've updated it to fake a user agent string by default.

> --honest
By default, nativefier uses a preset user agent string for your OS and masquerades as a regular Google Chrome browser, so that sites like WhatsApp Web will not say that the current browser is unsupported. If this flag is passed, it will not override the user agent.

You don't have to pass in any flags for WhatsApp to work now

**Comment by joserobleda** [comment]
Yes, I've noted this, and I think it is a better approach, but whatsapp web now always shows it is under unsupported browser, no matter what flags I use... 

Have you tested this site in particular?

**Comment by jiahaog** [comment]
Yeah I've tested it. Sorry about that, I completely forgot to publish my commit ><, it should be up already in v6.5.4

**Comment by joserobleda** [comment]
Don't worry, just to let you know, I've just downgraded to 6.4.0 and it works well meanwhile.

**Comment by jiahaog** [comment]
It should be working now with >v6.5.4, feel free to reopen this if you have issues.

**Comment by joserobleda** [comment]
Thanks, I'll check it in my next "install". Thank you very much!
