### ISSUE TITLE
Support starting minimized to tray (without window)

### ISSUE THREAD

**Issue by x3r4n0** [jiahaog/nativefier#522]
i know that is not an issue but for me it is.

i need a parameter who lets me start a wrapper directly into tray mode so that i only see it in tray not in taskbar.

i hope someone can help me or is it maybe a future feature?

**Comment by ronjouch** [comment]
> *i know that is not an issue but for me it is*

@x3r4n0 nope, sounds like a very valid issue / feature request to me 🙂.

> *i hope someone can help me or is it maybe a future feature?*

No active development happens currently in Nativefier, all new bugfixes and features are user-contributed. So, if you really want this feature, start your editor 🙂. I'll do my best to help.

- Regarding starting minimized to tray, Electron should let you do that.
- Regarding parameter handling, I think the lib we use will let you spruce up the `--tray` flag so that:
    - `nativefier ...` → no tray
    - `nativefier --tray` → tray
    - `nativefier --tray start-in-tray` → tray, initially minimized to tray

**Comment by x3r4n0** [comment]
with flag  ->>> --tray start-in-tray i got an error :-(

**Comment by ronjouch** [comment]
@x3r4n0 😄. Ah, my writing must have been unclear. This flag option doesn't exist, I was describing a command-line-interface change proposal, for you (or anyone else, or me if I need it someday) to implement.

**Comment by x3r4n0** [comment]
ahh okay :-/ my sadness that i cant programming :(

**Comment by x3r4n0** [comment]
@ronjouch maybe u can help me? :-/ is it much work to integrate it?

thank you in advance :-)

**Comment by ronjouch** [comment]
> *maybe u can help me? :-/ is it much work to integrate it? thank you in advance :-)*

Hey @x3r4n0.

* Start by [setting up a development environment](https://github.com/jiahaog/nativefier/blob/master/docs/development.md#development).
* Fiddle with it 🙂.
* Then, start following your way through the *build-time* code: `cli.js`, `options/optionsMain.js`, `build/build{App,Main}.js`. Tweak the options parsing so that your modified `tray` option contains your `start-in-tray` value.
* At this point, when building an app, your `app/nativefier.json` should contain a `"tray": "start-in-tray"` key/value pair.
* Then, update the *runtime* code `app/src/main.js` to start minimized when adequate. Look at [main.js, lines 105-108](https://github.com/jiahaog/nativefier/blob/master/app/src/main.js#L105-L108). See how currently we `mainWindow = createMainWindow(appArgs, app.quit, setDockBadge);` ? I guess we should do something a little different here, research the Electron API to make it start minimized.

Hope that helps! Give it a try! 🙂

**Comment by ooker777** [comment]
Hi @tribut and @ronjouch, I have a classic error:
    
    error: unknown option `--start-in-tray'

**Comment by ooker777** [comment]
Hi @tribut and @ronjouch, I have a classic error:

    error: unknown option `--start-in-tray'

For a general approach (not limited to apps made by Nativefier), visit [Where may setting about last opened window style be stored?](https://superuser.com/q/1377823/301042)

**Comment by ronjouch** [comment]
@ooker777 that's because @tribut 's code is still unmerged, as I had comments needing addressing.

**Comment by tribut** [comment]
Not much time currently. It's on my to-do. If you have the time, feel free to make changes to my PR.

**Comment by ooker777** [comment]
if so, is there a way to workaround this? I've tried using PowerShell but it doesn't work. 

    Start-Process -WindowStyle Minimized 'D:\GitHub\Web-wrapper\Google Keep-win32-ia32\Google Keep.exe'

**Comment by ronjouch** [comment]
Released in v7.6.9. Thanks @tribut !

**Comment by ooker777** [comment]
it seems that the flag `--maximize` will negate this flag? Is there a way to autostart the program in tray, but then open it maximally when open the window?
