### ISSUE TITLE
Badge Notification in Dock

### ISSUE THREAD

**Issue by frapporti** [jiahaog/nativefier#546]
### Description

Despite using --counter option, MacOs badge symbol is missing in the icon in the Dock.
Tried --badge but outcome does't change.

### Steps to reproduce issue

Build an app from a page that uses notifications, and receive messages.
The notification sound is played and the system notification appears, but icon doesn't display a red badge with notification count on it.

### Details

- Are you nativefying a *public* website?
Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Not a feature request, already checked in the help.
- Full nativefier command used to build your app: `nativefier --fast-quit --badge --counter --icon icon.icns --width 1008 --max-width 1008 --min-width 605 --name lightgram http://web.telegram.org ./ --inject lightgram.css --inject lightgram.js`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v9.4.0`
- OS: `macOs High Sierra 10.13.3`
- Error message / stack trace (if any):
```
no error
```

**Comment by digiltd** [comment]
I think this is due to web.telegram.org not showing a counter in the title bar which is required for the counter to work.

For example, Gmail shows the number in the titlebar like so...

![inbox 10 2018-02-28 19-38-50](https://user-images.githubusercontent.com/5680968/36809162-11f0ead4-1cbf-11e8-8544-f47d157350d0.png)

running `nativefier --fast-quit --counter --width 1008 --max-width 1008 --min-width 605 --name Gmail "https://mail.google.com"`

gives you...

![dock 2018-02-28 19-39-48](https://user-images.githubusercontent.com/5680968/36809221-37700fb0-1cbf-11e8-8e42-56431489dffa.png)

**Comment by ronjouch** [comment]
> *"I think this is due to web.telegram.org not showing a counter in the title bar which is required for the counter to work."*

Yup, the current mechanism is simply looking for something like `(18)` in the page title (which is a common convention).

So, @frapporti you could `--inject` a script that fetches that counter from wherever else it lives, and updates the page title.

**Comment by BroFox86** [comment]
I made my [inject.js](https://github.com/BroFox86/google-plus-app/blob/master/inject.js) for the Google Plus notification counter. Feel free to take a look and write your own one in a similar way.
