### ISSUE TITLE
How to bookmark pages from the same site to open in the current app?

### ISSUE THREAD

**Issue by edirpedro** [jiahaog/nativefier#576]
I'm using this with Facebook, but not only timeline, I use Facebook Tools, Developers, Ads Manager and so on. Could I create shortcuts from those sub-sites in the App, instead of creating one app for each site on Facebook?

I was thinking about bookmarks inside the app, or maybe the ability to create shortcuts on Mac OS to open the Facebook App with some link, like Developers website or Ads Manager.

**Comment by ronjouch** [comment]
@edirpedro nativefier is made to bundle a url, and it (sometimes) does it well. We don't aim at replicating a browser. If you need browser features, use a browser and, yes, your OS shortcut capabilities 🙂.

**Comment by bacongravy** [comment]
The fix for #405 (#574) might give you the tools you need to make this work; I think adding a custom URL handler to a nativefier app to support deep linking would let you save shortcuts that open the nativefier app and navigate to a specific sub-site.

**Comment by jacksellwood** [comment]
I traced through several issues and ended up here. Is this issue not on roadmap or even open? This seems incredibly useful for web apps like Google Docs/JIRA/Podio where clicking a link opens in the default brownser instead of within the corresponding nativified app. I tried using Choosy for basic URL handling, but nativefier doesn't accept URL CLI args like Chrome does. Would love to see this feature!
