### ISSUE TITLE
App content is blurry with HiDPI/4K resolutions under Windows

### ISSUE THREAD

**Issue by JohannesDeml** [jiahaog/nativefier#598]
### Description

With my 4K Display the complete ui in nativefier (except of the window bar) is blurry.
![image](https://user-images.githubusercontent.com/4518980/39702437-18265440-5205-11e8-97c9-d45f9b7b691a.png)

### Steps to reproduce issue

Try any app on windows with scaling higher than 100%
![image](https://user-images.githubusercontent.com/4518980/39702574-9fbf657c-5205-11e8-9f84-0d61ce5a07a8.png)
The text is not crisp (at least in my case).

### Details

- Version of Nativefier : `v7.4.1`
- OS: `Windows10`

**Comment by ronjouch** [comment]
@JohannesDeml I see quite a few [electron bug reports for that](https://www.google.ca/search?q=electron%20blurry%20hidpi), I suspect it's fixed in recent Electrons. Your Nativefier is old, and defaults to an old Electron. Please:

- Upgrade Nativefier and rebuild (7.6.2 will default to last stable Electron 1.8.6).
- If still problematic, try with super-recent Electron 2.0.0 (passing flag `-e 2.0.0`).
- If still problematic, please come back with the full command-line used to build and we'll re-open the issue 🙂.

**Comment by JohannesDeml** [comment]
@ronjouch Perfect, thanks a lot for the support! I can confirm that windows scaling is supported with nativefier@7.6.2 and node v8.11.1.
Used the basic command `nativefier --name "Asana" "http://asana.com"`
