### ISSUE TITLE
Redirects to my default browser

### ISSUE THREAD

**Issue by akash86167** [jiahaog/nativefier#632]
I made an app "Google search" with the help of command [ nativefier "https://google.com" ], but when I tried to open a website through google search like "Youtube" or "bing" it just redirects to my default browser and opens up the respective website there. Furthermore it is using an older version of chrome.
![z](https://user-images.githubusercontent.com/29308253/41109028-9a7a9824-6a93-11e8-9ac1-f31df8493e91.png)

**Comment by ronjouch** [comment]
@akash86167 

- *"when I tried to open a website through google search like "Youtube" or "bing" it just redirects to my default browser"*  
→ Expected behavior; see [`--internal-urls`](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#internal-urls) flag.
- *"it is using an older version of chrome"*  
→ No, the latest Nativefier uses the latest Electron which uses the latest Chrome stable. Feel free to use flag `-e` to specify the [Electron release](https://github.com/electron/electron/releases) you want. Note that once a Nativefier app is built, it won't update, unlike Chrome, and you have to re-build. The "having to rebuild" part is intended, but we should do a better job at warning users, see #556.
