### ISSUE TITLE
White Page

### ISSUE THREAD

**Issue by rchintapenta** [jiahaog/nativefier#645]
### Description

<After I get authenticated with my IBM email and password the app shows just a white screen "Federated Identity Endpoint" showing on the top.
<img width="1279" alt="screenshot at jul 03 11-45-36" src="https://user-images.githubusercontent.com/40785661/42201740-b26d5570-7eb6-11e8-8da0-9a385b772e02.png">

>

### Details

- Are you nativefying a *public* website? No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
Hi @rchintapenta. This is Nativefier, the software IBM Verse is based on. We Nativefier have no control on fixing IBM Verse. Please contact the support for IBM Verse with your problem, and please also tell them we'd welcome a patch enabling customizing the `Help → Report an issue` link (so that a. users like you can be directed to proper support, and b. we Nativefier aren't solicited with things we have no control on).

Thanks 🙂.
