### ISSUE TITLE
no tabs on linux

### ISSUE THREAD

**Issue by monkeydri** [jiahaog/nativefier#655]
### Description

I assume that tabs are supported, since an issue for tabs feature-request has already been closed long time ago [#116](https://github.com/jiahaog/nativefier/issues/116) and from some issues it seems that tabs are supported, ex in OSX : [#647](https://github.com/jiahaog/nativefier/issues/647).

However on linux (ubuntu 18.04) this is not the case, tabs open in new window.

### Steps to reproduce issue

middle-click or ctrl-click a internal link opens a new window instead of a new tab.
*links are not either considered as external URLs because they do not open in web browser but in nativefier.*

### Details

- Are you nativefying a *public* website ? => tried few websites, some hosted locally and some public websites.
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? => yes and I trired to specify `--internal-urls` but it did not change the behaviour.
- Full nativefier command used to build your app: `nativefier --name "Gitlab" --icon "/path/to/gitlab/icon.png" --internal-urls "https://mydomain.comgitlab/*" "https://mydomain.com/gitlab"`
- Version of Nativefier (run `nativefier --version`): `v7.6.4`
- Version of node.js (run `node --version`): `v9.2.0`
- OS: `Ubuntu 18.04`

**Comment by bacongravy** [comment]
The `nativefier` support for tabs comes from `electron`; support for native tabs in `electron` for macOS was added here: https://github.com/electron/electron/pull/9052

If `electron` gets updated to support tabs on more platforms then it should be relatively simple to add support for them to `nativefier`.

It would be possible to change how middle-click and ctrl-click behave in `nativefier`, to open external links in an external browser when native tabs are unavailable, but I'm not convinced such a change would provide value, since external links already open in an external browser when you left-click on them.  Being able to use middle-click to override the default "open externally" behavior seems useful to me.

**Comment by ronjouch** [comment]
@monkeydri 👍 to what @bacongravy said. See Release Notes for [Nativefier v7.6.3](https://github.com/jiahaog/nativefier/releases/tag/v7.6.3):

> - macOS: Add tabs, used automatically instead of windows (PR #579).
>   Provided by Electron and (so far) no available for Windows/Linux, contributions welcome.

**Comment by monkeydri** [comment]
alright, thanks fro your answer. It's a pity, as I don't think native tabs will be available on linux/windows anytime soon on Electron as there is no equivalent feature on them as macOS native tabs (ie. an option to display multiple windows from an app as tabs).

**Comment by mhgharieb** [comment]
@bacongravy Can the module [electron-tabs](https://github.com/brrd/electron-tabs) help to support tabbing in Linux?
