### ISSUE TITLE
Where do the cookies/metadata sit?

### ISSUE THREAD

**Issue by altryne** [jiahaog/nativefier#7]
I tried deleting an app after I was signed in to a specific service.

Created another app for the same service, and I was logged in there as well. 
How can I make sure I delete an app together with all resources such as cookies etc'?

**Comment by jiahaog** [comment]
Hi, sorry for the late reply, I was really busy with school. I believe the app data is stored in `~/Library/Application Support/<app-name>`, as specified in the [docs](https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname)

In any case, I've realised that all the packaged apps share the same app data directory, because they all share the same app name. I've fixed this in 0897432062304525c5d0d61559ba710d82fc41a0 so that apps are uniquely identified by the `app-name` parameter and have their own individual resource directory.
