### ISSUE TITLE
Review and adapt to electron 4.0 / 5.0 / 6.0 breaking changes

### ISSUE THREAD

**Issue by ronjouch** [jiahaog/nativefier#727]
It's that time again! ~4.0~ ~5.0~ 6.0 is out ([4.0 release notes](https://github.com/electron/electron/releases/tag/v4.0.0) , EDIT: [5.0 release notes](https://electronjs.org/blog/electron-5-0), [6.0 release notes](https://electronjs.org/blog/electron-6-0)).

- 4.0 has, from what I see, one breaking change:
    - Changed to the new single instance API. [#12782](https://github.com/electron/electron/pull/12782), [#14518](https://github.com/electron/electron/pull/14518)
- 5.0: TODO
- 6.0: TODO

Anyone up to do it? PR welcome.

Also,

- Closing the current window with <kbd>CmdOrCtrl</kbd>+<kbd>W</kbd> fails in 4.x.
- ~Consider trying to un-break https://github.com/jiahaog/nativefier/issues/703 .~

**Comment by nwoolls** [comment]
@ronjouch just taking a look at this - it seems like maybe both of the noted breaking changes have already been addressed? I see commit 479611ecc40ad25957a072fc70ccef4556ef1251 seems to have introduce / modified the single-instance code to be in-line with https://github.com/electron/electron/pull/12782, and I do not see any code calling the method deprecated in https://github.com/electron/electron/pull/14518.

I've made a handful of small changes in order to build with Electron 4 and optionally enable Dark Mode on Mojave. The only issues I am seeing so far are:

- The icon for the app is not correct, but rather is the stock Electron icon. However, I see the same thing if I just clone master and then build & use that. Works fine installing w/ npm.
- Using CMD+W doesn't "fail" per-se, but does quit the app rather than closing the window and leaving the app open.

Any pointers on the above would be appreciated. Would love to help if this is truly a "quick pick" :)

**Comment by ronjouch** [comment]
@nwoolls thanks for chiming in!

> * I've made a handful of small changes in order to build with Electron 4 and optionally enable Dark Mode on Mojave.
> * The icon for the app is not correct, but rather is the stock Electron icon. However, I see the same thing if I just clone master and then build & use that. Works fine installing w/ npm.

Cool, send a PR!

> * Using CMD+W doesn't "fail" per-se, but does quit the app rather than closing the window and leaving the app open.

For me under Linux, Ctrl+W still fails on 4.x (it doesn't do anything and doesn't quit). But I notice 5.0.0-beta.X doesn't have the problem, so unless someone fixes the situation on 4.x, my plan was to simply 4.x and bump the default Electron to 5.x once it's stable. If you have the time for that, feedback welcome about breakage in 5.0.0-beta.X. I didn't notice any, but my usage of Nativefier these days is *extremely* limited, so there's a high chance I'm missing regressions.

> Any pointers on the above would be appreciated. Would love to help if this is truly a "quick pick" :)

The `quick pick` label is only a wild guess and an attempt at attracting contributors, but I might be wrong 🙂. And sorry, PRs very welcome, but these days I don't have the time & will to help more actively, see [Issue #746 - ⚠ Read before asking: Nativefier is unmaintained, we need your help! ⚠](https://github.com/jiahaog/nativefier/issues/746).

**Comment by nwoolls** [comment]
@ronjouch PR is up at https://github.com/jiahaog/nativefier/pull/796

We can continue the conversation there if that makes sense.

**Comment by fuzzy76** [comment]
Just mentioning here that since Electron 3.x is EOL, this can lead to security issues.
