### ISSUE TITLE
Nativefier and security, privacy, anonymity

### ISSUE THREAD

**Issue by dln949** [jiahaog/nativefier#790]
I have a question about Nativefier:  

As I understand it - and I may be incorrect - Nativefier relies on an underlying Chromium browser.  

What level of security/privacy/anonymity is built in to that browser?  

How can a Nativefier user control that stuff?  

When I access web sites in the ordinary fashion via a web browser, I rely on add-ons I have installed in Firefox - e.g., DuckDuck Go Privacy Essentials as just one example - in order to monitor what kind of tracking is happening on a site, and to attempt to stop or block it.  How can a person exercise the same kind of control when using the executable produced by Natviefier?  

(I hope this makes sense and that I'm wording my question clearly - I don't know the exact terms to be using, I am not an expert in computer matters.)

**Comment by Zunawe** [comment]
Since Chromium is open source, you can research security and privacy on Chromium and apply all that knowledge here. Creating an app using nativefier is, for most purposes, the same as using unmodified Chromium to access a web page. A lot of it will come down to trusting the site you're on rather than the browser.

There are some options in the [api](https://github.com/jiahaog/nativefier/blob/master/docs/api.md) that might be useful, but nothing related to tracking I think. You could further configure settings through electron, but you'd have to add those configurations to the code yourself.

It is possible to add chrome extensions to an electron app, which could solve your issue depending on the nature of the extensions, but unfortunately there doesn't seem to be support for that in nativefier. It probably wouldn't be too much work to add it to the code for a one-off build, but I'm guessing that forking and editing the nativefier code wasn't the solution you hoped to hear.

**Comment by dln949** [comment]
You are correct, I know nothing about computer coding, so I would not do any of the editing you talk about.  

But, thanks for the information, I appreciate it.
