### ISSUE TITLE
Gents, what is it in aid of?

### ISSUE THREAD

**Issue by englishextra** [jiahaog/nativefier#96]
Yeah. Good stuff. Well-done. What I would have started from—what is it in aid of?

Can somebody related to the project really strictly confirm and write a clear README saying—use this tool when you need to achieve this and that. When I read issues I have my issues in mind and what I am going to accomplish. 

Really. Having followed for only two days the issues I realised that users of the script/project dont understand what they are going to achieve. Yeah, give me native-looking GUI!

In this issue I would suggest the authors of the project strictly and clearly describe WHEN one should use nativefier and who to present the output.

For distribution of your universal webapp - I'm afraid it won't do. The project/script. For simple wrapping and having this as a standalone app. Perhaps.

I use electron-prebuilt/packager/builder - at least I understand where they are heading. The task here is described but in my view is misused. There come those feature requests that may turn a project into an endless combine. Correct me if I'm wrong. Do criticize.

**Comment by josephdburdick** [comment]
I like having my email, mixcloud.com, and locahost:3000 window separated from my other browser instances and I also like to see my single page app displayed in a chromeless browser.

**Comment by englishextra** [comment]
@josephdburdick oh yeah. That's pretty clear and straitforward. I like it. So use it for your private wrappers not for production - this is where i'm gettibg at.

**Comment by momosby** [comment]
@englishextra I think it is really great for various purposes, such as slimming down my Browsers load (and unpinning many tabs) 
I like to handle the app-creation with mobile user agents, (and thus getting slim mobile-like apps)
Also great for coding/production to out source local host tabs and such....
It is just nice to get a lot more control over what "the web" should be on my desktop
![screeny](https://cloud.githubusercontent.com/assets/11959076/12594715/b747147e-c477-11e5-84b9-6114ac8964ff.png)

**Comment by jiahaog** [comment]
@englishextra Personally, I intended it to be a niffy little tool for people to run browser tabs, kinda like @momosby's screenshot with minimal setup. I also believe that you can use it to package certain single page apps for distribution, instead of having just a hyperlink to your app that users can maybe bookmark, your app is now sitting on the desktop/launcher of your user. Such an app would have much more visibility to the user as compared to being just another tab on my browser.

Perhaps you're right in that I should specify the focus of this tool and it would certainly help in scoping further development and feature requests, I'll get around to clarifying soon. That being said, I'm open to feedback on other use cases that I might have overlooked, it's always interesting to hear ideas from the community. I'm actually kind of busy with school, so development might be a little slower until the weekend.

**Comment by englishextra** [comment]
Thanks for the replies. Yeah, as I understand the tool is somewhat of a comforting utility almost for everyone experienced, not just exclusively for webapps devs.

**Comment by gavinengel** [comment]
The next time someone says they need Microsoft Word and Excel:

```
nativefier office.live.com/start/Word.aspx;
nativefier office.live.com/start/Excel.aspx
```

**Comment by gavinengel** [comment]
I also wonder if this could help with TDD, perhaps if I can point a Selenium IDE/Selenium Builder test at it.  Instead of running a Selenium server.
