### ISSUE TITLE
Microsoft Teams App | Desktop Notification Issue on MacOS

### ISSUE THREAD

**Issue by s-ahuja** [jiahaog/nativefier#972]
**Bug description**
Can't see desktop notifications from this new app, am able to see the desktop notifications from the browser window running MS Teams.

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing open & closed issues. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Steps to reproduce**
1. if someone sends a teams message, there is 

**Expected behavior**
Desktop Notification when a message is sent on teams

**Actual behavior**
No desktop notification. However, because i gave the parameter --counter and --bounce so it shows me the counter.

**Context**
Nativefier: 8.0.7
Node.js: - v13.12.0
Npm: - 6.14.4
OS: MacOS 10.15.4

**Comment by ronjouch** [comment]
@s-ahuja hi, thanks for the report 🙂. This isn't specific to MS Teams, notifications are currently broken, but fixed in master by https://github.com/jiahaog/nativefier/commit/1d3bed5f09961e878c4c40085bd69aa2159d3a4c . It's unreleased yet, please do a [developer build](https://github.com/jiahaog/nativefier/blob/master/docs/development.md) if you need it or wait for the next release. I don't know when the next release will happen.
