### ISSUE TITLE
redirectURL doesn't work

### ISSUE THREAD

**Issue by heyimyunyl** [jiahaog/nativefier#973]
.

**Comment by hajimbae** [comment]
Anyone????

**Comment by hajimbae** [comment]
thanks...

**Comment by heyimyunyl** [comment]
????

**Comment by heyimyunyl** [comment]
instead of marking my comments as off-topic, a help would be nice?

**Comment by heyimyunyl** [comment]
keep marking my comments as off-topic, your program doesnt even work

**Comment by ronjouch** [comment]
@heyimyunyl stop being a GitHub troll.

I hide all "Anyone?" / "+1" / "Me too" / "It's still broken" comments because they only add noise, they don't contribute anything, and they won't help anyone find an answer. Actually, they make it _harder_ for potential contributors to help you, because the signal is lost in noise.

Also, this is not "my program", it's a piece of software I'm helping maintain. And as [documented in each recent release](https://github.com/jiahaog/nativefier/releases), I'm not doing any active development (and neither is the original author). Quoting my last blurb from a few weeks ago:

> 👋 And a reminder: dear users / contributors! Public service announcement!
> 
> Nativefier is maintained by YOU. It's reasonably sane to hack on since
> the 8.x cleanup, it fits the use cases needed by the original author and
> the current maintainer, so _we_ are not doing any active development.
> 
> But it's not dead! If YOU use it and want to see juicy features & fixes,
> PR welcome! In particular, here are three particularly annoying issues;
> help welcome on those (or any other issue that motivates you 🙂):
> 
> - https://github.com/jiahaog/nativefier/issues/902
> - https://github.com/jiahaog/nativefier/issues/831
> - https://github.com/jiahaog/nativefier/issues/706
> - For other issues, https://github.com/jiahaog/nativefier/issues
> 
> Thanks! Take care.

The best way to get help is to do research, to write something detailed with a good title, providing clear information to other users who might help you. But your useless comments are unwelcome. I'll re-open this thread in one week, so that other users able to help you can do so.

**Comment by heyimyunyl** [comment]
lmao
